version: '3.9'
services:
  app:
    build: .   
    image: job-app-image        
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
