version: '3.9'
services:
  app:
    build: .   
    image: job-app-image        
    ports:
      - "3000:3000"
    environment:
      MONGODB_URL: mongodb://mongo:27017/jobs-api
      JWT_SECRET: 943f2601c579e118e1fa1299ed3623221e869c3d6df6e5511e9775079f1b5336
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
